// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STLAF.Api.Data;

#nullable disable

namespace STLAF.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.ClientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("client_accounts", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.ClientPortalAdminGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("client_portal_admin_grants", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_config_json");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("TemplateFileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_file_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("client_portal_document_templates", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.FormSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fields_json");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "Version")
                        .IsUnique();

                    b.ToTable("client_portal_form_schemas", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.GeneratedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("client_portal_generated_documents", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("client_portal_services", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FormSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("form_schema_version");

                    b.Property<string>("ResponsesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("responses_json");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId");

                    b.HasIndex("ServiceId");

                    b.ToTable("client_portal_submissions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VoucherCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_code_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId")
                        .IsUnique();

                    b.HasIndex("VoucherCodeId");

                    b.ToTable("client_portal_subscriptions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.VoucherCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("PlanGrants")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_grants");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedByClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_client_account_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VoucherExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voucher_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("client_portal_voucher_codes", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.DocumentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date");

                    b.Property<string>("DocumentLink")
                        .HasColumnType("text")
                        .HasColumnName("document_link");

                    b.Property<DateTime?>("EaDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ea_decided_at");

                    b.Property<Guid?>("EaDecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ea_decided_by_employee_id");

                    b.Property<string>("EaDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("ea_decision_notes");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("file_object_key");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PartnerDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("partner_decided_at");

                    b.Property<Guid?>("PartnerDecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_decided_by_employee_id");

                    b.Property<string>("PartnerDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("partner_decision_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("document_requests", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeFullAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("intake_full_access_grants", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RecipientEmails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_emails");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("intake_groups", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("intake_services", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ClientConcerns")
                        .HasColumnType("text")
                        .HasColumnName("client_concerns");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_type");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consultation_date");

                    b.Property<string>("ConsultationPreference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consultation_preference");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<string>("HowDidYouFindUs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("how_did_you_find_us");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<string>("NumberOfEmployees")
                        .HasColumnType("text")
                        .HasColumnName("number_of_employees");

                    b.Property<string>("PreferredTimeSlots")
                        .HasColumnType("text")
                        .HasColumnName("preferred_time_slots");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupportingDocumentFileName")
                        .HasColumnType("text")
                        .HasColumnName("supporting_document_file_name");

                    b.Property<string>("SupportingDocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("supporting_document_url");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("intake_submissions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeSubmissionService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("intake_submission_services", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.ModuleAccessPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.Property<string>("OfficePosition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office_position");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Module", "OfficePosition")
                        .IsUnique();

                    b.ToTable("module_access_positions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.SmtpSender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppPasswordValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_password");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("smtp_senders", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("Bday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bday");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text")
                        .HasColumnName("companyemail");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("OfficePosition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("officeposition");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("text")
                        .HasColumnName("personalemail");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("hr_employees", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.EmployeeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("hr_employee_categories", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.EmployeeLeaveCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Credits")
                        .HasColumnType("numeric")
                        .HasColumnName("credits");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId")
                        .IsUnique();

                    b.ToTable("hr_employee_leave_credits", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApproverEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_employee_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("Department")
                        .IsUnique();

                    b.ToTable("hr_leave_approvers", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveNotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SmtpSenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("smtp_sender_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SmtpSenderId");

                    b.ToTable("hr_leave_notification_settings", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Days")
                        .HasColumnType("numeric")
                        .HasColumnName("days");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_employee_id");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("decision_notes");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RetractionDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retraction_decided_at");

                    b.Property<Guid?>("RetractionDecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("retraction_decided_by_employee_id");

                    b.Property<string>("RetractionDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("retraction_decision_notes");

                    b.Property<string>("RetractionReason")
                        .HasColumnType("text")
                        .HasColumnName("retraction_reason");

                    b.Property<DateTime?>("RetractionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retraction_requested_at");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("RetractionDecidedByEmployeeId");

                    b.ToTable("hr_leave_requests", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultCredits")
                        .HasColumnType("numeric")
                        .HasColumnName("default_credits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RequiresMedicalAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("requires_medical_after_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("hr_leave_types", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.MedicalCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriveFileId")
                        .HasColumnType("text")
                        .HasColumnName("drive_file_id");

                    b.Property<string>("DriveFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("drive_file_url");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text")
                        .HasColumnName("verification_notes");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_employee_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("VerifiedByEmployeeId");

                    b.ToTable("hr_medical_certificates", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.OvertimePartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<Guid>("PartnerEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_employee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Department")
                        .IsUnique();

                    b.HasIndex("PartnerEmployeeId");

                    b.ToTable("hr_overtime_partners", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeptDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dept_decided_at");

                    b.Property<Guid?>("DeptDecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dept_decided_by_employee_id");

                    b.Property<string>("DeptDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("dept_decision_notes");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision")
                        .HasColumnName("hours");

                    b.Property<DateTime?>("PartnerDecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("partner_decided_at");

                    b.Property<Guid?>("PartnerDecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_decided_by_employee_id");

                    b.Property<string>("PartnerDecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("partner_decision_notes");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeptDecidedByEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerDecidedByEmployeeId");

                    b.ToTable("hr_overtime_requests", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.UndertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_employee_id");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("decision_notes");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision")
                        .HasColumnName("hours");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("hr_undertime_requests", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.AppPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppPasswordValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_password");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GwsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gws_account_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("GwsAccountId");

                    b.ToTable("it_app_passwords", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_tag");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_name");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<bool>("HasKeyboard")
                        .HasColumnType("boolean")
                        .HasColumnName("has_keyboard");

                    b.Property<bool>("HasMonitor")
                        .HasColumnType("boolean")
                        .HasColumnName("has_monitor");

                    b.Property<bool>("HasMouse")
                        .HasColumnType("boolean")
                        .HasColumnName("has_mouse");

                    b.Property<string>("KeyboardSerial")
                        .HasColumnType("text")
                        .HasColumnName("keyboard_serial");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("MonitorSerial")
                        .HasColumnType("text")
                        .HasColumnName("monitor_serial");

                    b.Property<string>("MouseSerial")
                        .HasColumnType("text")
                        .HasColumnName("mouse_serial");

                    b.Property<string>("PreviousUser")
                        .HasColumnType("text")
                        .HasColumnName("previous_user");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Qr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.ToTable("it_assets", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfReplacement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_replacement");

                    b.Property<DateTime?>("DatePurchased")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_purchased");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartComponent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_component");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("it_asset_history", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.EmailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GwsAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("gws_account_id");

                    b.Property<string>("LocalGmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_gmail");

                    b.Property<string>("OldStlafEmail")
                        .HasColumnType("text")
                        .HasColumnName("old_stlaf_email");

                    b.Property<string>("OldUser")
                        .HasColumnType("text")
                        .HasColumnName("old_user");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<bool>("Recycled")
                        .HasColumnType("boolean")
                        .HasColumnName("recycled");

                    b.Property<DateTime?>("RecycledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recycled_at");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StlafEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stlaf_email");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("GwsAccountId");

                    b.ToTable("it_email_accounts", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.GwsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("gws_accounts", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_submitted");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_employee_id");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("ViberNumber")
                        .HasColumnType("text")
                        .HasColumnName("viber_number");

                    b.HasKey("Id");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("it_tickets", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.DocumentTemplate", b =>
                {
                    b.HasOne("STLAF.Api.ClientPortal.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.FormSchema", b =>
                {
                    b.HasOne("STLAF.Api.ClientPortal.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.GeneratedDocument", b =>
                {
                    b.HasOne("STLAF.Api.ClientPortal.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.Submission", b =>
                {
                    b.HasOne("STLAF.Api.ClientPortal.Entities.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.ClientPortal.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientAccount");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("STLAF.Api.ClientPortal.Entities.Subscription", b =>
                {
                    b.HasOne("STLAF.Api.ClientPortal.Entities.ClientAccount", "ClientAccount")
                        .WithMany()
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.ClientPortal.Entities.VoucherCode", "VoucherCode")
                        .WithMany()
                        .HasForeignKey("VoucherCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientAccount");

                    b.Navigation("VoucherCode");
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeService", b =>
                {
                    b.HasOne("STLAF.Api.Common.Entities.IntakeGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeSubmissionService", b =>
                {
                    b.HasOne("STLAF.Api.Common.Entities.IntakeService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Common.Entities.IntakeSubmission", "Submission")
                        .WithMany("SelectedServices")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.Employee", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.EmployeeCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.EmployeeLeaveCredit", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveApprover", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveNotificationSetting", b =>
                {
                    b.HasOne("STLAF.Api.Common.Entities.SmtpSender", "SmtpSender")
                        .WithMany()
                        .HasForeignKey("SmtpSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmtpSender");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.LeaveRequest", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "DecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("DecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "RetractionDecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("RetractionDecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DecidedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("RetractionDecidedByEmployee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.MedicalCertificate", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.LeaveRequest", "LeaveRequest")
                        .WithMany()
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "VerifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("VerifiedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");

                    b.Navigation("LeaveRequest");

                    b.Navigation("VerifiedByEmployee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.OvertimePartner", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "PartnerEmployee")
                        .WithMany()
                        .HasForeignKey("PartnerEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PartnerEmployee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "DeptDecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("DeptDecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "PartnerDecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("PartnerDecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeptDecidedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("PartnerDecidedByEmployee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.HRAdmin.Entities.UndertimeRequest", b =>
                {
                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "DecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("DecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("STLAF.Api.Departments.HRAdmin.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DecidedByEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.AppPassword", b =>
                {
                    b.HasOne("STLAF.Api.Departments.IT.Entities.GwsAccount", "GwsAccount")
                        .WithMany()
                        .HasForeignKey("GwsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GwsAccount");
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.AssetHistory", b =>
                {
                    b.HasOne("STLAF.Api.Departments.IT.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("STLAF.Api.Departments.IT.Entities.EmailAccount", b =>
                {
                    b.HasOne("STLAF.Api.Departments.IT.Entities.GwsAccount", "GwsAccount")
                        .WithMany()
                        .HasForeignKey("GwsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GwsAccount");
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("STLAF.Api.Identity.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.User", b =>
                {
                    b.HasOne("STLAF.Api.Identity.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STLAF.Api.Identity.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("STLAF.Api.Common.Entities.IntakeSubmission", b =>
                {
                    b.Navigation("SelectedServices");
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("STLAF.Api.Identity.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
